import keyMirror from "keymirror";

const _events = {
  "MENU_CLICK_CMD": "MENU_CLICK_CMD",
  "MENU_CLICK_EVT": "MENU_CLICK_EVT",  
  "SEGMENT_UPDATE_CMD": "SEGMENT_UPDATE_CMD",
  'SEGMENT_UPDATE_EVT': "SEGMENT_UPDATE_EVT",  
  'SEGMENT_CLONE_CMD': "SEGMENT_CLONE_CMD",
  'SEGMENT_CLONE_EVT': "SEGMENT_CLONE_EVT",
  "SEGMENT_ADD_CMD": "SEGMENT_ADD_CMD",
  "SEGMENT_ADD_EVT": "SEGMENT_ADD_EVT",
  "SEGMENT_REMOVE_CMD": "SEGMENT_REMOVE_CMD",
  "SEGMENT_REMOVE_EVT": "SEGMENT_REMOVE_EVT",
  "PLAN_LOAD_CMD": "PLAN_LOAD_CMD",
  "PLAN_LOAD_EVT": "PLAN_LOAD_EVT",
  "TRAINING_LIST_EVT": "TRAINING_LIST_EVT",
  "TRAINING_LIST_CMD": "TRAINING_LIST_CMD",
  "TRAINING_LOAD_CMD": "TRAINING_LOAD_CMD",
  "TRAINING_LOAD_EVT": "TRAINING_LOAD_EVT"
};

export default _events;